name: thai_safe
description: "Community safety reporting for Thailand."
publish_to: "none"
version: 1.1.0+2

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.2.1
  google_fonts: ^7.1.0

  firebase_core: ^4.12.1
  cloud_firestore: ^6.7.1
  firebase_auth: ^6.5.6
  firebase_storage: ^13.4.5
  cloud_functions: ^6.3.5
  firebase_messaging: ^16.4.3
  firebase_app_check: ^0.4.5+2
  firebase_crashlytics: ^5.2.6
  firebase_analytics: ^12.4.5
  firebase_remote_config: ^6.5.5

  flutter_map: ^8.3.1
  latlong2: ^0.10.1
  geolocator: ^11.0.0
  geohash_plus: ^1.1.1
  geocoding: ^4.0.0
  url_launcher: ^6.3.2

  image_picker: ^1.0.7
  permission_handler: ^11.3.0
  uuid: ^4.5.2
  shared_preferences: ^2.5.5
  sqflite: ^2.4.2+1
  workmanager: ^0.9.0+3
  flutter_native_splash: ^2.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/common/logo.jpg
  android_12:
    color: "#FFFFFF"
    image: assets/images/common/logo.jpg
  fullscreen: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/common/logo.jpg
    - assets/images/welcome/fireman.png
    - assets/images/welcome/data_engineer.png
    - assets/images/welcome/rescue.png
    - assets/images/auth/ThaiID.png
