// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3KvZFjTdY9H2bIuxXSIj11VqJli_Riao',
    appId: '1:796274817197:web:16e348d173a68f2d53ee24',
    messagingSenderId: '796274817197',
    projectId: 'thai-safe-967b9',
    authDomain: 'thai-safe-967b9.firebaseapp.com',
    storageBucket: 'thai-safe-967b9.firebasestorage.app',
    measurementId: 'G-23FLPLKKWS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbx9F6I496rCgbUZXUtehCMvZNZcI-87U',
    appId: '1:796274817197:android:eae1a4a9899b91dd53ee24',
    messagingSenderId: '796274817197',
    projectId: 'thai-safe-967b9',
    storageBucket: 'thai-safe-967b9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDjAFwF-roupZR_2ovmqpYWqfaZOEo5n0',
    appId: '1:796274817197:ios:eb50c7958a88b55c53ee24',
    messagingSenderId: '796274817197',
    projectId: 'thai-safe-967b9',
    storageBucket: 'thai-safe-967b9.firebasestorage.app',
    iosBundleId: 'com.example.thaiSafe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDjAFwF-roupZR_2ovmqpYWqfaZOEo5n0',
    appId: '1:796274817197:ios:eb50c7958a88b55c53ee24',
    messagingSenderId: '796274817197',
    projectId: 'thai-safe-967b9',
    storageBucket: 'thai-safe-967b9.firebasestorage.app',
    iosBundleId: 'com.example.thaiSafe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3KvZFjTdY9H2bIuxXSIj11VqJli_Riao',
    appId: '1:796274817197:web:aa81ba04f0196d8553ee24',
    messagingSenderId: '796274817197',
    projectId: 'thai-safe-967b9',
    authDomain: 'thai-safe-967b9.firebaseapp.com',
    storageBucket: 'thai-safe-967b9.firebasestorage.app',
    measurementId: 'G-8L661P8EZF',
  );
}
